BASE = ../../../../git/botop/rai
BASE2 = ../../../../git/botop

DEPEND = KOMO Core Geo Kin Gui Optim

INCL = -I./include

LIBS += -lpthread -I/usr/local/include/opencv4

OBJS = main.o src/CameraRecorder.o
CPPFLAGS += -I/usr/include/opencv4


include $(BASE)/_make/generic.mk